export const NEXT_LINE_CHARACTER = '\u{0085}';
export const LATIN_SMALL_LETTER_E_WITH_ACUTE = '\u{00E9}';
const COMBINING_GRAVE_ACCENT = '\u{0300}';
const COMBINING_ACUTE_ACCENT = '\u{0301}';
export const GREEK_SMALL_LETTER_BETA = '\u{03B2}';

export const DEVANAGARI_LETTER_KA = '\u{0915}';
const DEVANAGARI_LETTER_JA = '\u{091C}';
const DEVANAGARI_LETTER_NYA = '\u{091E}';
const DEVANAGARI_LETTER_SSA = '\u{0937}';
const DEVANAGARI_SIGN_VIRAMA = '\u{094D}';

export const THAI_CHARACTER_KO_KAI = '\u{0E01}';
const THAI_CHARACTER_KHO_KHAI = '\u{0E02}';
const THAI_CHARACTER_CHO_CHAN = '\u{0E08}';
const THAI_CHARACTER_CHO_CHING = '\u{0E09}';
const THAI_CHARACTER_NO_NU = '\u{0E19}';
const THAI_CHARACTER_MO_MA = '\u{0E21}';
const THAI_CHARACTER_RO_RUA = '\u{0E23}';
const THAI_CHARACTER_WO_WAEN = '\u{0E27}';
const THAI_CHARACTER_MAI_HAN_AKAT = '\u{0E31}';
const THAI_CHARACTER_SARA_AA = '\u{0E32}';
const THAI_CHARACTER_SARA_I = '\u{0E34}';
const THAI_CHARACTER_MAI_THO = '\u{0E49}';

const ZERO_WIDTH_JOINER = '\u{200D}';
export const LINE_SEPARATOR = '\u{2028}';
export const PARAGRAPH_SEPARATOR = '\u{2029}';
const COMBINING_ENCLOSING_KEYCAP = '\u{20E3}';
const AIRPLANE = '\u{2708}';
export const SPARKLES = '\u{2728}';
const VARIATION_SELECTOR_15 = '\u{FE0E}';
const VARIATION_SELECTOR_16 = '\u{FE0F}';

const REGIONAL_INDICATOR_SYMBOL_LETTER_N = '\u{1F1F3}';
const REGIONAL_INDICATOR_SYMBOL_LETTER_S = '\u{1F1F8}';
const REGIONAL_INDICATOR_SYMBOL_LETTER_U = '\u{1F1FA}';
const LIGHT_SKIN_TONE = '\u{1F3FB}';
const MEDIUM_SKIN_TONE = '\u{1F3FD}';
const THUMBS_UP_SIGN = '\u{1F44D}';
const BOY = '\u{1F466}';
const GIRL = '\u{1F467}';
const MAN = '\u{1F468}';
const WOMAN = '\u{1F469}';
const PERSONAL_COMPUTER = '\u{1F4BB}';
const MICROSCOPE = '\u{1F52C}';
export const SLIGHTLY_SMILING_FACE = '\u{1F642}';

export const E_WITH_COMBINING_GRAVE = `e${COMBINING_GRAVE_ACCENT}`;
export const E_WITH_COMBINING_ACUTE = `e${COMBINING_ACUTE_ACCENT}`;

export const DEVANAGARI_KSSA = DEVANAGARI_LETTER_KA + DEVANAGARI_SIGN_VIRAMA + DEVANAGARI_LETTER_SSA;
export const DEVANAGARI_KSSA_WITH_ZWJ =
  DEVANAGARI_LETTER_KA + DEVANAGARI_SIGN_VIRAMA + ZERO_WIDTH_JOINER + DEVANAGARI_LETTER_SSA;
export const DEVANAGARI_JNYA = DEVANAGARI_LETTER_JA + DEVANAGARI_SIGN_VIRAMA + DEVANAGARI_LETTER_NYA;

export const THAI_CHO_CHING_WITH_MAI_HAN_AKAT = THAI_CHARACTER_CHO_CHING + THAI_CHARACTER_MAI_HAN_AKAT;
export const THAI_PRONOUN_I = THAI_CHO_CHING_WITH_MAI_HAN_AKAT + THAI_CHARACTER_NO_NU;
const THAI_EAT = THAI_CHARACTER_KO_KAI + THAI_CHARACTER_SARA_I + THAI_CHARACTER_NO_NU;
const THAI_RICE = THAI_CHARACTER_KHO_KHAI + THAI_CHARACTER_MAI_THO + THAI_CHARACTER_SARA_AA + THAI_CHARACTER_WO_WAEN;
export const THAI_ACTIVITY =
  THAI_CHARACTER_KO_KAI +
  THAI_CHARACTER_SARA_I +
  THAI_CHARACTER_CHO_CHAN +
  THAI_CHARACTER_KO_KAI +
  THAI_CHARACTER_RO_RUA +
  THAI_CHARACTER_RO_RUA +
  THAI_CHARACTER_MO_MA;
export const THAI_EAT_RICE = THAI_EAT + THAI_RICE;
export const THAI_BEFORE = THAI_PRONOUN_I + THAI_EAT_RICE;
export const THAI_AFTER = THAI_PRONOUN_I + THAI_ACTIVITY + THAI_EAT_RICE;
export const THAI_RAW_EQUALITY_PREFIX = THAI_PRONOUN_I + THAI_CHARACTER_KO_KAI + THAI_CHARACTER_SARA_I;
export const THAI_RAW_INSERTION =
  THAI_CHARACTER_CHO_CHAN +
  THAI_CHARACTER_KO_KAI +
  THAI_CHARACTER_RO_RUA +
  THAI_CHARACTER_RO_RUA +
  THAI_CHARACTER_MO_MA +
  THAI_CHARACTER_KO_KAI +
  THAI_CHARACTER_SARA_I;
export const THAI_RAW_EQUALITY_SUFFIX = THAI_CHARACTER_NO_NU + THAI_RICE;

export const AIRPLANE_EMOJI_STYLE = AIRPLANE + VARIATION_SELECTOR_16;
export const AIRPLANE_TEXT_STYLE = AIRPLANE + VARIATION_SELECTOR_15;
export const KEYCAP_ONE = `1${VARIATION_SELECTOR_16}${COMBINING_ENCLOSING_KEYCAP}`;
export const KEYCAP_TWO = `2${VARIATION_SELECTOR_16}${COMBINING_ENCLOSING_KEYCAP}`;
export const UNITED_NATIONS_FLAG = REGIONAL_INDICATOR_SYMBOL_LETTER_U + REGIONAL_INDICATOR_SYMBOL_LETTER_N;
export const UNITED_STATES_FLAG = REGIONAL_INDICATOR_SYMBOL_LETTER_U + REGIONAL_INDICATOR_SYMBOL_LETTER_S;
export const THUMBS_UP_LIGHT_SKIN_TONE = THUMBS_UP_SIGN + LIGHT_SKIN_TONE;
export const THUMBS_UP_MEDIUM_SKIN_TONE = THUMBS_UP_SIGN + MEDIUM_SKIN_TONE;
export const WOMAN_TECHNOLOGIST = WOMAN + ZERO_WIDTH_JOINER + PERSONAL_COMPUTER;
export const WOMAN_SCIENTIST = WOMAN + ZERO_WIDTH_JOINER + MICROSCOPE;
export const WOMAN_SCIENTIST_MEDIUM_SKIN_TONE = WOMAN + MEDIUM_SKIN_TONE + ZERO_WIDTH_JOINER + MICROSCOPE;
export const MAN_WOMAN_GIRL_BOY_FAMILY =
  MAN + ZERO_WIDTH_JOINER + WOMAN + ZERO_WIDTH_JOINER + GIRL + ZERO_WIDTH_JOINER + BOY;
export const WOMAN_WOMAN_GIRL_BOY_FAMILY =
  WOMAN + ZERO_WIDTH_JOINER + WOMAN + ZERO_WIDTH_JOINER + GIRL + ZERO_WIDTH_JOINER + BOY;
